theme: bento
languageCode: en-us
baseurl: "/"
title: dssquad
author: The dssquad Team
copyright: dssquad
taxonomies:
  category: categories
  disqusShortname: bento-hugo-theme
  googleAnalytics: UA-XXXXXX-YY
  pygmentsCodefences: yes
  pygmentsStyle: vs
  tag: tags
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    style: github
params:
  authorBio: This is a documentation site for a data product being developed.
  avatar: images/avatar.jpg
  copyright: Copyright © 2020 dssquad
  cover: images/vancouver.jpg
  description: This is a documentation site for a data product being developed.
  email: email@xxxx.com
  fathomAnalytics:
    serverURL: analytics.example.com
    siteID: XXXXX
  github: XXXX
  headline: Data Product Documentation
  intro: yes
  linkedin: https://linkedin.com/in/XXXX
  ogImage: images/og_image.jpg
  twitter: XXXX
  umami:
    siteID: XXXXX
    trackerScript: //umami.example.com/umami.js
menu:
  main:
    - name: About
      url: /about
      weight: 1
    - name: Archives
      url: /archives
      weight: 1
    - name: Meet The Team
      url: https://github.com/leonardofaria/bento
      weight: 1
