baseurl: "/"
title: Data Science Squad Product Documentation
theme: ghostwriter
languageCode: en-us
copyright: dssquad
disqusShortname: XXX
googleAnalytics: XXX
pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: dssquad
  profile: ""

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: Data Science Squad
  description: We are a diverse, global team of data professionals who organized for the experience of engineering an open source, production-grade data science application.
  github: "https://github.com/Data-Science-Squad"
  opengraph: true
  shareTwitter: true
  rss: true
  shareFacebook: true
  shareLinkedIn: false
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""
  # If you want to use plausible(https://plausible.io) for analytics, add this section
  plausibleAnalytics:
    domain: ""
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL: ""

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /page/about/
      weight: 2
    - name: Meet The Team
      url: /page/meettheteam/
      weight: 3
    - name: Blog
      url: /post/
      weight: 4
    - name: Contact
      url: /page/contact/
      weight: 4