baseurl: "/"
title: HOME
theme: ghostwriter
languageCode: en-us
copyright: dssquad
disqusShortname: XXX
googleAnalytics: UA-192424916-1
pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: dssquad
  profile: ""

taxonomies:
  tag: tags

params:
  mainSections:
    - homepage
  intro: true
  headline: DATA SCIENCE SQUAD
  description: WE ARE A DIVERSE, GLOBAL TEAM OF DATA PROFESSIONALS WHO ORGANIZED FOR THE EXPERIENCE OF ENGINEERING AN OPEN SOURCE, PRODUCTION-GRADE DATA SCIENCE APPLICATION.
  github: "https://github.com/Data-Science-Squad"
  opengraph: true
  shareTwitter: true
  shareFacebook: true
  shareLinkedIn: true
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Reading time:"
  fathomUrl: ""
  fathomSiteId: ""
  # If you want to use plausible(https://plausible.io) for analytics, add this section
  plausibleAnalytics:
    domain: ""
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL: ""

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: ABOUT THE FORECAST-HUB PROJECT
      url: /about-the-project
      weight: 1
    - name: MEET THE TEAM
      url: /meet-the-team
      weight: 2
    - name: ARTICLES
      url: /post/
      weight: 3
